// Mocks generated by Mockito 5.4.4 from annotations
// in movie_flutter/test/test_utils/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_flutter/api/models.dart' as _i6;
import 'package:movie_flutter/api/movies_repository.dart' as _i3;
import 'package:movie_flutter/common/result.dart' as _i5;
import 'package:result_monad/src/result_monad_base.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E> extends _i1.SmartFake implements _i2.Result<T, E> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRepository extends _i1.Mock implements _i3.MoviesRepository {
  MockMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i2.Result<_i5.PagedContent<List<_i6.MovieSummary>>, dynamic>> movies(
          int? currentPage) =>
      (super.noSuchMethod(
        Invocation.method(
          #movies,
          [currentPage],
        ),
        returnValue: _i4.Future<
                _i2.Result<_i5.PagedContent<List<_i6.MovieSummary>>,
                    dynamic>>.value(
            _FakeResult_0<_i5.PagedContent<List<_i6.MovieSummary>>, dynamic>(
          this,
          Invocation.method(
            #movies,
            [currentPage],
          ),
        )),
      ) as _i4.Future<
          _i2.Result<_i5.PagedContent<List<_i6.MovieSummary>>, dynamic>>);

  @override
  _i4.Future<_i2.Result<_i6.Movie, dynamic>> movie(String? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #movie,
          [movieId],
        ),
        returnValue: _i4.Future<_i2.Result<_i6.Movie, dynamic>>.value(
            _FakeResult_0<_i6.Movie, dynamic>(
          this,
          Invocation.method(
            #movie,
            [movieId],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i6.Movie, dynamic>>);
}
