// Mocks generated by Mockito 5.4.4 from annotations
// in movie_flutter/test/test_utils/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:chopper/chopper.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:movie_flutter/api/repositories/models/movie.dart' as _i7;
import 'package:movie_flutter/api/repositories/models/movie_summary.dart'
    as _i6;
import 'package:movie_flutter/api/repositories/movies_repository.dart' as _i3;
import 'package:movie_flutter/common/result.dart' as _i5;
import 'package:result_monad/src/result_monad_base.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T, E> extends _i1.SmartFake implements _i2.Result<T, E> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRepository extends _i1.Mock implements _i3.MoviesRepository {
  MockMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<
      _i2.Result<_i5.PagedContent<List<_i6.MovieSummary>>, dynamic>> getMovies(
          int? currentPage) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMovies,
          [currentPage],
        ),
        returnValue: _i4.Future<
                _i2.Result<_i5.PagedContent<List<_i6.MovieSummary>>,
                    dynamic>>.value(
            _FakeResult_0<_i5.PagedContent<List<_i6.MovieSummary>>, dynamic>(
          this,
          Invocation.method(
            #getMovies,
            [currentPage],
          ),
        )),
      ) as _i4.Future<
          _i2.Result<_i5.PagedContent<List<_i6.MovieSummary>>, dynamic>>);

  @override
  _i4.Future<_i2.Result<_i7.Movie, dynamic>> get(int? movieId) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [movieId],
        ),
        returnValue: _i4.Future<_i2.Result<_i7.Movie, dynamic>>.value(
            _FakeResult_0<_i7.Movie, dynamic>(
          this,
          Invocation.method(
            #get,
            [movieId],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i7.Movie, dynamic>>);

  @override
  _i2.Result<T, dynamic> toResult<T>(_i8.Response<T>? response) =>
      (super.noSuchMethod(
        Invocation.method(
          #toResult,
          [response],
        ),
        returnValue: _FakeResult_0<T, dynamic>(
          this,
          Invocation.method(
            #toResult,
            [response],
          ),
        ),
      ) as _i2.Result<T, dynamic>);

  @override
  _i4.Future<_i2.Result<T, dynamic>> handleResult<T>(
          _i4.Future<_i2.Result<T, dynamic>> Function()? doRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #handleResult,
          [doRequest],
        ),
        returnValue:
            _i4.Future<_i2.Result<T, dynamic>>.value(_FakeResult_0<T, dynamic>(
          this,
          Invocation.method(
            #handleResult,
            [doRequest],
          ),
        )),
      ) as _i4.Future<_i2.Result<T, dynamic>>);

  @override
  _i4.Future<_i2.Result<T, dynamic>> responseToResult<T>(
          _i4.Future<_i8.Response<T>> Function()? doRequest) =>
      (super.noSuchMethod(
        Invocation.method(
          #responseToResult,
          [doRequest],
        ),
        returnValue:
            _i4.Future<_i2.Result<T, dynamic>>.value(_FakeResult_0<T, dynamic>(
          this,
          Invocation.method(
            #responseToResult,
            [doRequest],
          ),
        )),
      ) as _i4.Future<_i2.Result<T, dynamic>>);
}
