name: movie_flutter
description: "List movies and information around them"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: 3.4.3
  flutter: 3.22.2

dependencies:
  built_collection: 5.1.1
  built_value: 8.9.2
  cached_network_image: 3.4.1
  chopper: 8.0.1+1
  flutter:
    sdk: flutter
  hive_built_value_flutter:
    # Adding from git because the author has not made the update to pub.dev
    git:
      url: git@github.com:martipello/hive_built_value.git
      path: hive_built_value_flutter
      ref: 3daa1858effbbd94b0aa5b87b8277d3871a75152
  http: 1.2.2
  intl: 0.19.0
  logger: 2.4.0
  provider: 6.1.2
  result_monad: 2.3.2
  shimmer: 3.0.0

dev_dependencies:
  build_runner: 2.4.11 # 2.4.12 is not compatible
  built_value_generator: 8.9.2
  chopper_generator: 8.0.1
  collection: 1.18.0
  dart_code_linter: 1.1.3
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter
  hive_built_value_generator:
    # Adding from git because the author has not made the update to pub.dev
    git:
      url: git@github.com:martipello/hive_built_value.git
      path: hive_built_value_generator
      ref: 3daa1858effbbd94b0aa5b87b8277d3871a75152
  intl_utils: 2.8.7
  mockito: 5.4.4
  timezone: 0.9.4
  uuid: 4.4.2
  very_good_analysis: 6.0.0

dependency_overrides:
  file: ^7.0.0 # avoid conflict with dart_code_linter and cached_network_image

flutter:
  uses-material-design: true
